# Generated by Django 5.1.5 on 2025-07-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
