# Generated by Django 5.1.5 on 2025-02-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_approval_date_employee_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
