# Generated by Django 5.1.5 on 2025-02-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_date_joined_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reset_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
