# Generated by Django 5.2.1 on 2025-07-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_work_experience'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')])),
                ('comment', models.TextField(help_text='Share your work experience and feedback')),
                ('work_environment', models.BooleanField(default=False, help_text='Work environment and culture')),
                ('salary_benefits', models.BooleanField(default=False, help_text='Salary and benefits package')),
                ('career_growth', models.BooleanField(default=False, help_text='Career growth opportunities')),
                ('work_life_balance', models.BooleanField(default=False, help_text='Work-life balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employer.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employer.job')),
            ],
            options={
                'verbose_name': 'Job Review',
                'verbose_name_plural': 'Job Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'job')},
            },
        ),
    ]
