# Generated by Django 5.1.5 on 2025-07-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_jobreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobReview',
        ),
    ]
