# Generated by Django 5.1.5 on 2025-02-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_reset_code_employee_reset_code_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reset_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reset_code_created',
        ),
    ]
