# Generated by Django 5.2.1 on 2025-07-31 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeefeedback'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeefeedback',
            old_name='compensation',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='management',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='work_environment',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='work_life_balance',
        ),
        migrations.AlterField(
            model_name='employeefeedback',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeefeedback',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='employer.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='employer.job')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('job', 'employee', 'employer')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='employee.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
