# Generated by Django 5.1.5 on 2025-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_user_alter_employee_id_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee_resumes/'),
        ),
    ]
