# Generated by Django 5.2 on 2025-05-31 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('job_type', models.CharField(default='Any Job Type', max_length=50)),
                ('work_arrangement', models.CharField(default='Any Arrangement', max_length=50)),
                ('skills', models.JSONField()),
                ('experience', models.IntegerField(default=0)),
                ('current_role_years', models.CharField(default='Any Duration', max_length=50)),
                ('education_level', models.CharField(default='Any Education Level', max_length=50)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('salary_min', models.IntegerField(default=15000)),
                ('salary_max', models.IntegerField(default=150000)),
                ('availability', models.CharField(default='Any Availability', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
