# Generated by Django 5.2.5 on 2025-11-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_feedback_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
