# Generated by Django 5.2 on 2025-05-31 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_jobpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpreferences',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to='employee.employee'),
        ),
    ]
