# Generated by Django 5.2.1 on 2025-07-21 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_notification'),
        ('employer', '0016_remove_employer_registration_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='employee',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employer.job'),
        ),
    ]
