# Generated by Django 5.2.1 on 2025-07-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_rename_employee_notification_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
