# Generated by Django 5.2.1 on 2025-07-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_notification'),
        ('employer', '0016_remove_employer_registration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='employer.job'),
        ),
    ]
