# Generated by Django 5.1.5 on 2025-07-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_savedjob'),
        ('employer', '0016_remove_employer_registration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, help_text='Jobs this employee has saved/bookmarked.', related_name='saved_by_employees', to='employer.job'),
        ),
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
