# Generated by Django 5.1.5 on 2025-07-23 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_employee_saved_jobs_delete_savedjob'),
        ('employer', '0016_remove_employer_registration_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='saved_jobs',
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='employee.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_employees', to='employer.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'job')},
            },
        ),
    ]
