# Generated by Django 5.1.5 on 2025-07-24 12:26

import django.db.models.deletion
import django.utils.timezone
import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_description', models.TextField(blank=True)),
                ('company_website', models.URLField(blank=True)),
                ('company_location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('registration_types', models.CharField(blank=True, help_text='Selected registration types', max_length=255)),
                ('business_permit', models.FileField(blank=True, help_text='Upload your business permit (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='business_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('registration_document', models.FileField(blank=True, help_text='Upload your SEC/DTI registration document (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='registration_documents/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('registration_number', models.CharField(blank=True, help_text='Your SEC/DTI registration number', max_length=50)),
                ('registration_date', models.DateField(blank=True, help_text='Date of SEC/DTI registration', null=True)),
                ('barangay_clearance', models.FileField(blank=True, help_text='Upload your Barangay Clearance (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='barangay_clearances/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('mayors_permit', models.FileField(blank=True, help_text="Upload your Mayor's Permit (PDF, JPG, JPEG, or PNG, max 10MB)", null=True, upload_to='mayors_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('bir_certificate', models.FileField(blank=True, help_text='Upload your BIR Certificate (Form 2303) (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='bir_certificates/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('sanitary_permit', models.FileField(blank=True, help_text='Upload your Sanitary Permit (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='sanitary_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('fda_permit', models.FileField(blank=True, help_text='Upload your FDA Permit (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='fda_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('labeling_compliance', models.FileField(blank=True, help_text='Upload your DTI or FDA Labeling Compliance (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='labeling_compliance/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size])),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], max_length=20)),
                ('work_setup', models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20)),
                ('description', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Junior', 'Junior'), ('Mid Level', 'Mid Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Expert', 'Expert')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applications_count', models.IntegerField(default=0)),
                ('requirements', models.TextField(blank=True, help_text='List the job requirements')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('scheduled_interview', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Job Offered'), ('hired', 'Hired'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('employer_notes', models.TextField(blank=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_applications', to='employee.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.job')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
