# Generated by Django 5.1.5 on 2025-01-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
