# Generated by Django 5.1.5 on 2025-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_employer_work_setup_job_work_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_setup',
            field=models.CharField(choices=[('on-site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20),
        ),
    ]
