# Generated by Django 5.1.5 on 2025-02-22 12:03

import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_job_work_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Upload your business permit (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='business_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='registration_date',
            field=models.DateField(blank=True, help_text='Date of SEC/DTI registration', null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='registration_document',
            field=models.FileField(blank=True, help_text='Upload your SEC/DTI registration document (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='registration_documents/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employer',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Your SEC/DTI registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('SEC', 'SEC Registration'), ('DTI', 'DTI Registration')], max_length=3),
        ),
    ]
