# Generated by Django 5.1.5 on 2025-02-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
