# Generated by Django 5.1.5 on 2025-02-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_employer_business_permit_employer_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
