# Generated by Django 5.1.5 on 2025-02-16 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_employer_latitude_employer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
