# Generated by Django 5.1.5 on 2025-03-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_employer_approval_date_employer_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='List the job requirements'),
        ),
    ]
