# Generated by Django 5.1.5 on 2025-03-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='job',
            name='longitude',
        ),
    ]
