# Generated by Django 5.1.5 on 2025-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_job_latitude_remove_job_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Junior', 'Junior'), ('Mid Level', 'Mid Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Expert', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], max_length=20),
        ),
    ]
