# Generated by Django 5.1.5 on 2025-03-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_job_experience_level_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_setup',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20),
        ),
    ]
