# Generated by Django 5.1.5 on 2025-03-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_avatar_employee_full_name_and_more'),
        ('employer', '0011_alter_job_work_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('scheduled_interview', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Job Offered'), ('hired', 'Hired'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('employer_notes', models.TextField(blank=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.job')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
