# Generated by Django 5.1.5 on 2025-03-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_user_alter_employee_id_jobapplication'),
        ('employer', '0012_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_applications', to='employee.employee'),
        ),
    ]
