# Generated by Django 5.1.5 on 2025-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_alter_jobapplication_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_setup',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote')], max_length=20),
        ),
    ]
