# Generated by Django 5.2 on 2025-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_alter_job_work_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_setup',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20),
        ),
    ]
