# Generated by Django 5.1.5 on 2025-06-13 01:53

import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_job_latitude_job_longitude_alter_job_work_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='registration_type',
        ),
        migrations.AddField(
            model_name='employer',
            name='barangay_clearance',
            field=models.FileField(blank=True, help_text='Upload your Barangay Clearance (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='barangay_clearances/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employer',
            name='bir_certificate',
            field=models.FileField(blank=True, help_text='Upload your BIR Certificate (Form 2303) (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='bir_certificates/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employer',
            name='fda_permit',
            field=models.FileField(blank=True, help_text='Upload your FDA Permit (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='fda_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employer',
            name='labeling_compliance',
            field=models.FileField(blank=True, help_text='Upload your DTI or FDA Labeling Compliance (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='labeling_compliance/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employer',
            name='mayors_permit',
            field=models.FileField(blank=True, help_text="Upload your Mayor's Permit (PDF, JPG, JPEG, or PNG, max 10MB)", null=True, upload_to='mayors_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employer',
            name='registration_types',
            field=models.CharField(blank=True, help_text='Selected registration types', max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='sanitary_permit',
            field=models.FileField(blank=True, help_text='Upload your Sanitary Permit (PDF, JPG, JPEG, or PNG, max 10MB)', null=True, upload_to='sanitary_permits/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
    ]
