"""
Django settings for capstoneforever project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Add NLTK data path for production environments
import nltk
nltk.data.path.append('/opt/nltk_data')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=48g(rt0qfx6y333(sy!j2h&l)7tn*o$ru4q6rk$u%yx+5#a3%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employee',
    'employer',
    'landing',
    'admin_panel',
    'django_bootstrap5',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'capstoneforever.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            os.path.join(BASE_DIR, 'dist') # Tell Django where to find the Vue app's index.html
        ],
        'APP_DIRS': True,  # This should be True to allow loading templates from app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]


WSGI_APPLICATION = 'capstoneforever.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration
def build_database_url():
    url = (
        os.environ.get('DATABASE_URL')
        or os.environ.get('SUPABASE_DB_URL')
        or os.environ.get('POSTGRES_URL')
        or os.environ.get('PGDATABASE_URL')
    )

    if url:
        return url

    db_name = os.environ.get('DB_NAME')
    db_user = os.environ.get('DB_USER')
    db_password = os.environ.get('DB_PASSWORD')
    db_host = os.environ.get('DB_HOST')
    db_port = os.environ.get('DB_PORT', '5432')

    if all([db_name, db_user, db_password, db_host]):
        return f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"

    return None


DATABASE_URL = build_database_url()

if not DATABASE_URL:
    raise ImproperlyConfigured(
        "DATABASE configuration is missing. Provide DATABASE_URL or DB_NAME/DB_USER/DB_PASSWORD/DB_HOST."
    )

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=os.environ.get('DATABASE_SSL_REQUIRE', 'True').lower() == 'true'
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'employee/static/dist'),
    os.path.join(BASE_DIR, 'employee/static/dist/assets')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Add this to allow Vue.js to make API calls to Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
]

# In production, you'll need to allow your Railway app's domain.
# You can add this to your environment variables on Railway.
if 'CORS_ALLOWED_ORIGINS_DEPLOY' in os.environ:
    CORS_ALLOWED_ORIGINS.extend(os.environ.get('CORS_ALLOWED_ORIGINS_DEPLOY', '').split(','))

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8080').split(',')

# Allow iframe embedding for document viewing in admin panel
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Message tags
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

LOGIN_URL = 'admin_panel:login'  # Redirect protected admin routes to the custom admin login

# Email Configuration
# Priority: Resend API (for Railway/production) > SMTP (fallback for local development)
# Resend is used when RESEND_API_KEY is set in environment variables
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Fallback for local dev
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_TIMEOUT = 15  # 15 seconds timeout for SMTP connection
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# Set DEFAULT_FROM_EMAIL from environment variable
# For Resend: Use a verified domain or Resend's default domain (onboarding@resend.dev)
# Format: 'Display Name <email@example.com>' or just 'email@example.com'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')
if not DEFAULT_FROM_EMAIL:
    # Use Resend's default domain for testing (no verification needed)
    # For production, verify your domain in Resend dashboard and use: 'Geoconnect <noreply@yourdomain.com>'
    DEFAULT_FROM_EMAIL = 'Geoconnect <onboarding@resend.dev>'

# Only override DEFAULT_FROM_EMAIL for SMTP (Gmail) if RESEND_API_KEY is NOT set
# When using Resend, we should use Resend's domain, not Gmail
if not os.environ.get('RESEND_API_KEY') and EMAIL_HOST_USER and DEFAULT_FROM_EMAIL:
    # Extract email from DEFAULT_FROM_EMAIL if it's in format "Name <email>"
    import re
    email_match = re.search(r'<(.+?)>', DEFAULT_FROM_EMAIL)
    if email_match:
        from_email_addr = email_match.group(1)
    else:
        from_email_addr = DEFAULT_FROM_EMAIL
    
    # If the email doesn't match EMAIL_HOST_USER, update it (only for SMTP/Gmail)
    if from_email_addr != EMAIL_HOST_USER:
        print(f"[EMAIL CONFIG] Using SMTP: Updating DEFAULT_FROM_EMAIL to use EMAIL_HOST_USER for Gmail compatibility")
        DEFAULT_FROM_EMAIL = f'Geoconnect <{EMAIL_HOST_USER}>'
elif os.environ.get('RESEND_API_KEY'):
    # When using Resend, ensure we're using Resend's domain
    import re
    if DEFAULT_FROM_EMAIL:
        email_match = re.search(r'<(.+?)>', DEFAULT_FROM_EMAIL)
        if email_match:
            from_email_addr = email_match.group(1)
        else:
            from_email_addr = DEFAULT_FROM_EMAIL
        
        # If DEFAULT_FROM_EMAIL is using Gmail domain, switch to Resend default
        if '@gmail.com' in from_email_addr or '@googlemail.com' in from_email_addr:
            print(f"[EMAIL CONFIG] Using Resend: Switching from Gmail to Resend default domain")
            DEFAULT_FROM_EMAIL = 'Geoconnect <onboarding@resend.dev>'

# Password Reset Settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds

# Custom User Model
AUTH_USER_MODEL = 'admin_panel.AdminUser'
